### ISSUE TITLE
Make sure MySQL connection string is read from env var

### ISSUE THREAD

**Issue by liptanbiswas** [neetusuthar90/URL-Shortener-Service#9]
Read this mysql connection string from env variables

https://github.com/neetusuthar90/URL-Shortener-Service/blob/3234200b398853270d3157913aecc3fb193fb94e/backend/app.py#L13

**Comment by neetusuthar90** [comment]
Fixed in https://github.com/neetusuthar90/URL-Shortener-Service/commit/6d355838577f85413c69f983c68e07a60a5da228
